language: java
script: mvn clean install -P prod
deploy:
  on:
    tags: true
  overwrite: true
  provider: releases
  api_key:
    secure: Kpx1uy4KpOsXOBScZ4dPqyQUicuvbvA348XAolbUaLHT41MjS3bKRI6/wB91ze52T+TUi7OKdxXRqDAyWhsxsJrsyz/pG8GxZc8IuPVIPzf+dqDw6uSouEDCyRW15UOAxDfpNEtiQwHiRQy7DfWQrkYwsLoQ1ohMPWZcKUmCFBH95OFrsejNk+xcxadQ8E8lFfnHB77/+GqljenCYnsGUaQJXa5J8OUr1nob36/5Q099UbcRoQXv3p1FBBB9nhguo1n/HBUeMVkB9yrmBUHGOBdeCwx4X/t16KzM10pFRbsT+VsP2dIdTMVOMIjSX5xZ+R9STXFJqKHMHFJBR5DUy+XNF628tBYD87mKbH5LsNa2/mtx+HvyGE9VqurjjAk73/hN9XsYdmoiwQCAHvA0i319oCzo/Y3KwIG0MhzkL9To089GWTWecK9LlldWt0RWvjRkZV5U5AfwK8RSPfw513K8bEka6tqQeQVfP+TxQ7lBfaOGRwl35hrkuA8aM7yN3Pu5hYw8TvzN2STgRb+it2wkIxIVEToe4d/rpfkoxUodM6CbV4M+VnZFN9OSkEiRzhWqCB57Y2OTdj/VYWdBevOG73D9zNu3K/I8Dkg6DtLlQ6Bp8VtrJvKJghVLgFWgwyR2Tm+jtggM32JyAmsY6cQuu+gQu2g0DjPo37R6fOE=
  file: ./target/wololo-bot.jar
  skip_cleanup: true
  draft: true
